load(":rules.bzl", "my_pipeline", "my_pipeline_zip")

my_pipeline(
    name = "pipeline",
    src = "//resources:data.json",
)

# Point 4 
my_pipeline_zip(
    name = "pipeline_zip",
    src = "//resources:data.json",
)